# -*- coding: utf-8 -*-
"""prob_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gP84WGJ-Kwr5NJD1efqaZ2G2CGOb91pF
"""

t = int(input())
while(t!=0):
    n=int(input())
    lst=list(map(int,input().split()))
    a=min(lst)
    b=max(lst)
    count=0
    if a in lst:
        d=lst.index(a)
        if(len(lst[:d+1])>len(lst[d:])):
            for i in lst[d:]:
                lst.remove(i)
                count=count+1
        
        if(len(lst[:d+1])<=len(lst[d:])):
            for i in lst[:d+1]:
                lst.remove(i)
                count=count+1
    
    if b in lst:
        e=lst.index(b)
        if(len(lst[:e+1])>len(lst[e:])):
            for i in lst[e:]:
                lst.remove(i)
                count=count+1
        
        if(len(lst[:e+1])<=len(lst[e:])):
            for i in lst[:e+1]:
                lst.remove(i)
                count=count+1
    
    print(count)        
    t=t-1