# -*- coding: utf-8 -*-
"""prob_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OxVc-8WnR1a-GvxsX-OLmf7397lk2yS8
"""

def uglyvalue(lst,value):
    sum=0
    for i in range(len(lst)):
        if(i==0):
            sum=sum+lst[0]
        
        elif(i==(len(lst)-1)):
            sum=sum+abs(lst[i]-lst[i-1])+lst[-1]
            
        else:
            if(lst[i+1]==0):
                if(lst[i]==0):
                    sum=sum+lst[i]
                else:
                    sum=sum+abs(lst[i]-lst[i-1])+lst[i]
            else:
                sum=sum+abs(lst[i]-lst[i-1])
             
    return(sum+value)

t = int(input())
while(t!=0):
    n=int(input())
    lst=list(map(int,input().split()))
    l=[]
    v1=0
    x=uglyvalue(lst,v1)
    l.append(x)
    a=max(lst)
    #print(a)
    p=lst.index(a)
    lst[p]=a-1
    v2=1
    y=uglyvalue(lst,v2)
    l.insert(0,y)
    while(l[0]!=l[1]):
        c=max(lst)
        q=lst.index(c)
        lst[q]=c-1
        v2=v2+1
        z=uglyvalue(lst,v2)
        l.insert(0,z)
        
    print(min(l))
    t=t-1