# -*- coding: utf-8 -*-
"""rnyati_prob_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYKbik4uj_hZm55cz6EO2OvBmMumVcDk
"""

n,q=map(int,input().split())
s=str(input())

while(q!=0):
    sum=0
    l,r=map(int,input().split())
    x=s[l-1:r]
    for i in x:
        if(i=='a'):
            c=1
        elif(i=='b'):
            c=2
        elif(i=='c'):
            c=3
        elif(i=='d'):
            c=4
        elif(i=='e'):
            c=5
        elif(i=='f'):
            c=6
        elif(i=='g'):
            c=7
        elif(i=='h'):
            c=8
        elif(i=='i'):
            c=9
        elif(i=='j'):
            c=10
        elif(i=='k'):
            c=11
        elif(i=='l'):
            c=12
        elif(i=='m'):
            c=13
        elif(i=='n'):
            c=14
        elif(i=='o'):
            c=15
        elif(i=='p'):
            c=16
        elif(i=='q'):
            c=17
        elif(i=='r'):
            c=18
        elif(i=='s'):
            c=19
        elif(i=='t'):
            c=20
        elif(i=='u'):
            c=21
        elif(i=='v'):
            c=22
        elif(i=='w'):
            c=23
        elif(i=='x'):
            c=24
        elif(i=='y'):
            c=25
        elif(i=='z'):
            c=26
            
        sum=sum+c
    print(sum)
    q=q-1