# -*- coding: utf-8 -*-
"""rnyati_prob_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYKbik4uj_hZm55cz6EO2OvBmMumVcDk
"""

n,q=map(int,input().split())
s=str(input())
lst = list(map(chr, range(97, 123)))
#print(lst)
#l=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
while(q!=0):
    sum=0
    l,r=map(int,input().split())
    x=s[l-1:r]
    for i in x:
        #print(i)
        h2=int(lst.index(i))
        #print(h2)
        sum=sum+h2+1
    print(sum)
    q=q-1