# -*- coding: utf-8 -*-
"""rohan_p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tps7xXEJOnPkuQ5b-p7ExChD42dutQ3T
"""

t=int(input())
while(t!=0):
    n=int(input())
    a=(n/3)
    c2=int(a)
    c1=c2+1
    l=[c1,c2]
    print(*l)
    t=t-1