# -*- coding: utf-8 -*-
"""Summer_Heat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5sKjKNJYIPUSaxkcko2iPXhVkUBEKNk
"""

t = int(input())

while(t!=0):
    n=input()
    lst=list(map(int,n.split()))
    x=int(lst[2]//lst[0])
    y=int(lst[3]//lst[1])
    print(x+y)
    t=t-1