# -*- coding: utf-8 -*-
"""Leetcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cxzUuqTyu0dzD9bLNl53_IUfHZ6J33GC
"""

t=int(input())
lst=[]
#lst2=[]
lst1=[]
i=0
while(t!=0):
  n=int(input())
  t=t-1
  for i in range(n):
    k=(n-i-1)
    lst.append(k)
    if(i==0):
      x=(n-i) and k
      lst1.append(x)
    y = lst1[i] and k 
    lst1.append(y)
    if(y==0):
      z=lst[-1]+1
      print(z)
      #lst2.append(z)
      break
#print('\n'.join(map(str, lst2)))