# -*- coding: utf-8 -*-
"""RohanNyati.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TSvCoKVbml3MuV1T_9OysYGL0YkhBjPK
"""

t = int(input())
while(t!=0):
    n=int(input())
    nums=list(map(int,input().split()))
    lst=list(nums)
    y=min(nums)
    #print(y)
    count=0
    for i in range(len(nums)):
      #print(nums[i])
      if(nums[i]!=y):
          lst.remove(nums[i])
          count=count+1

      #print(lst)
    print(count)
    t=t-1