# -*- coding: utf-8 -*-
"""rnyati_prob_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYKbik4uj_hZm55cz6EO2OvBmMumVcDk
"""

n,q=map(int,input().split())
s=str(input())
lst = list(map(chr, range(97, 123)))
while(q!=0):
    sum=0
    l,r=map(int,input().split())
    x=s[l-1:r]
    l1=[i for i in x]
    set1=set(l1)
    #print(set1)
    for i in set1 :
        h2=int(lst.index(i))+1
        c=l1.count(i)
        sum=sum+(h2*c)
    print(sum)
    q=q-1