# -*- coding: utf-8 -*-
"""rohan_problem_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wU-W3b-WOoeEHUgx6ByVVXVFPtzvrH0p
"""

t = int(input())

while(t!=0):
    n=input()
    lst=list(map(int,n.split()))
    #print(lst)
    lst1=list(lst)
    x=max(lst)
    lst1.remove(x)
    y=max(lst1)
    lst2=[y,x]
    lst3=[]
    if(lst[0]>lst[1]):
        lst3.append(lst[0])
    if(lst[1]>lst[0]):
        lst3.append(lst[1])
    if(lst[2]>lst[3]):
        lst3.append(lst[2]) 
    if(lst[3]>lst[2]):
        lst3.append(lst[3])
    lst3.sort()
    if(lst3==lst2):
        print("YES")
    else:
        print("NO")
    
    t=t-1